export const metadata = {
  title: 'Yasmin Mostoller | Privacy Policy',
  description: 'Privacy Policy for yasminmostoller.com',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-[90vh] flex items-center justify-center p-4 bg-[var(--background-primary)]">
      <div className="w-full max-w-screen-xl mx-auto mt-4 p-6 bg-[var(--background-secondary)] rounded-lg shadow-lg">
        <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-6">Privacy Policy</h1>
        <div className="space-y-4 text-[var(--text-secondary)]">
          <section>
            <h2 className="text-xl font-semibold mb-2">1. Information Collection</h2>
            <p>
              We collect basic profile information provided by Google OAuth when you sign in to comment on our
              blog posts. This includes your name and email address. Additionally, we use Google Analytics to
              collect anonymous usage data to help us understand how visitors interact with our website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">2. Use of Information</h2>
            <p>
              Profile information is used solely for user authentication and display of your name with your
              comments. Analytics data helps us improve our website and content. We do not combine analytics
              data with your personal information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">3. Data Storage</h2>
            <p>
              Your basic profile information and comments are stored securely. We do not sell or share your
              personal information with third parties. Analytics data is processed by Google Analytics
              according to their privacy policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">4. Cookies</h2>
            <p>
              We use essential cookies for maintaining your login session and Google Analytics cookies to
              collect anonymous usage data. You can opt out of analytics cookies through your browser settings
              or using Google&apos;s opt-out browser add-on.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">5. Analytics</h2>
            <p>
              This website uses Google Analytics, a web analytics service provided by Google, Inc. Google
              Analytics uses cookies to help us analyze how users use the site. The information generated by
              the cookie about your use of the website will be transmitted to and stored by Google on servers
              in the United States.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">6. Your Rights</h2>
            <p>
              You can request deletion of your account and comments at any time. You can also opt out of
              Google Analytics tracking. Contact us for any privacy-related concerns.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
